### ISSUE TITLE
Invalid environment variable

### ISSUE THREAD

**Issue by brian-bason** [saucelabs/bamboo_sauce#14]
Environment variable SAUCE_ONDEMAND_BROWSERS is being populated in variable with name bamboo_SAUCE_ONDEMAND_BROWSERS instaead. The documentation on the Sauce Lab site indicate that the parameter should be SAUCE_ONDEMAND_BROWSERS

**Comment by rossrowe** [comment]
Just a quick update, the documentation has now been updated, but there still doesn't appear to be an answer to the [question](https://answers.atlassian.com/questions/298615/create-bamboo-global-variables-without-prefix)
