### ISSUE TITLE
Viewing Sauce Labs Results in Bamboo

### ISSUE THREAD

**Issue by jtalon21** [saucelabs/bamboo_sauce#22]
Hello,

Could you clear something up for me? In order to view the Sauce Labs results in Bamboo, do you first need to be logged into Sauce Labs in a different tab? OR, is it not required to be logged into Sauce Labs  at all to view the results.

Thanks,

Jeff

**Comment by rossrowe** [comment]
Closing this issue, but please let me know if this is still a problem
