### ISSUE TITLE
Unable to install bamboo-sauce on Bamboo OnDemand instances

### ISSUE THREAD

**Issue by cerdman** [saucelabs/bamboo_sauce#25]
Currently this plugin is only available for the Server / on-premise version of Bamboo? My bamboo cloud instance will not let me install this.

**Comment by rossrowe** [comment]
Hi, we've raised this with Atlassian several times, and the advice they've provided is that Bamboo OnDemand doesn't currently support installation of third-party plugins.  We'll touch base with them again to see if anything has changed at their end.
