### ISSUE TITLE
Bug when selecting "Enable Sauce OnDemand"

### ISSUE THREAD

**Issue by albedithdiaz** [saucelabs/bamboo_sauce#26]
One of our customers at Sauce Labs noticed that If they leave the "Enable Sauce OnDemand" option in Bamboo unchecked, everything works fine. But if they check the "Enable Sauce OnDemand" option then the plugin uses incorrect desired capabilities for their test.

The correct desired capabilities for a test can be found here: https://docs.saucelabs.com/reference/platforms-configurator/#/

**Comment by rossrowe** [comment]
Hi, do you have any further details on the specific browser(s) selected by the user?  The list of browsers supplied by the Bamboo plugin is retrieved from the Sauce REST API, and which might not have a 1:1 correspondence with the correct capabilities to be used, so if there's a specific browser with an issue, I can update the plugin to cater for it.
