### ISSUE TITLE
cannot pass bamboo env variables via the plugin

### ISSUE THREAD

**Issue by skadadi** [saucelabs/bamboo_sauce#27]
I cannot use bamboo env variables with Sauce Connect Options. So when I say -i ${bamboo.buildNumber}
The bamboo variables dont get populated. I always have to use some hard-coded value.

**Comment by rossrowe** [comment]
Hi, this feature has been included in version 1.6.60 of the plugin

**Comment by skadadi** [comment]
Thanks Ross but this partially fixes my problem and creates some other problems.

1) The tunnel does not close once started if I use a bamboo variable -i ${bamboo.buildNumber} even after the tests are done. I guess the teardown routine for sauce connect also needs to be updated.

2) I cannot use multiple bamboo variables. eg- "-i ${bamboo.buildNumber}_${bamboo.buildKey}" does not work.

**Comment by skadadi** [comment]
Hey are we going to fix these problems. I am blocked on this especially when I need to run tests in parallel on different branches.

**Comment by jsmoxon** [comment]
Sorry for the delayed response. I'm a PM at Sauce Labs. We will look into this and get back to you. 
Thanks for your patience.

**Comment by jtalon21** [comment]
@jsmoxon Appreciate if we could get a fix in asap on this.

**Comment by halkeye** [comment]
@jtalon21 @skadadi this should now be live in 1.6.65
