### ISSUE TITLE
Bamboo build log output needs to be consistent with Jenkins

### ISSUE THREAD

**Issue by arazasplunk** [saucelabs/bamboo_sauce#31]
We use both Bamboo and Jenkins. When run saucelabs enabled jobs in Jenkins, we get very detailed logs showing what exactly in happening in saucelabs, what version of sauceconnect is being used ,etc. This output is very useful when debugging issues. 

Bamboo build logs barely have a single line about what is happening in saucelabs. I can't even tell if test are running in local browser or saucelabs.

The saucelabs build output needs be standardized across both Jenkins and Bamboo as much as technically possible.

**Comment by jsmoxon** [comment]
Can you provide more detail as to what specifically you want to see in a verbose log?

**Comment by arazasplunk** [comment]
Similar to jenkins output.

Ali

**Comment by halkeye** [comment]
This should now be addressed in 1.6.63
cc @jsmoxon
