### ISSUE TITLE
When will the plugin support bamboo 5.9.7?

### ISSUE THREAD

**Issue by lleiguo** [saucelabs/bamboo_sauce#32]
When I try to install this plugin into Bamboo 5.9.7 but it says it's not compatible with the current version of bamboo and the plugin will not activate.

**Comment by jdesulme** [comment]
This plugin is currently holding us back on upgrading. Can we get compatibility verified for this?

**Comment by foal** [comment]
:+1:

**Comment by halkeye** [comment]
This is being worked on right now. We just got the code compiling again with the latest atlassian sdk.

**Comment by halkeye** [comment]
This has been released, I'm closing the issue.
