### ISSUE TITLE
Tunnel does not close when I use bamboo env variables via the plugin

### ISSUE THREAD

**Issue by skadadi** [saucelabs/bamboo_sauce#34]
1) The tunnel does not close once started if I use a bamboo variable -i ${bamboo.buildNumber} even after the tests are done. I guess the teardown routine for sauce connect also needs to be updated.

2) I cannot use multiple bamboo variables. eg- "-i ${bamboo.buildNumber}_${bamboo.buildKey}" does not work.

**Comment by halkeye** [comment]
The newest release should be out soon. From my tests this has been fixed, but I'd appreciate you upgrading to 649 when its public and checking
