### ISSUE TITLE
Platform list sauce connect provides is not the same ones that sauce lab expects

### ISSUE THREAD

**Issue by vprajapa** [saucelabs/bamboo_sauce#9]
There are couple of issues.
1. SELENIUM_PLATFORM value for windows provides server version instead of desktop version that sauce lab expects.
2. When selecting multiple choices for Webdriver browsers, platform names are incorrect for every platform. For example, sauce lab supported browsers page shows OS X 10.9 for platform however the environment values shows following,
"platform":"MAC", "os":"Mac 10.9",
I know these are being populated by the REST response, is there a workaround for this?

**Comment by rossrowe** [comment]
Sorry for taking so long to reply to this issue - the value of the SELENIUM_PLATFORM environment variable is retrieved from the Sauce REST API (the footnote on https://saucelabs.com/platforms/ indicates that server versions are used for licensing purposes).  The 'platform' value in the SAUCE_ONDEMAND_BROWSERS environment variable corresponds to the Selenium Platform enum value, and the 'os' corresponds to the value retrieved from the Sauce REST API - the 'os' value should be used when developing tests to be run against Sauce Labs.
